name: release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;

    - name: run build.sh
      shell: bash
      run:
          sh build.sh

