name: release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;
        gcc --version
        bazel --version

    - name: Build
      shell: bash
      run: bazel build examples:all
