name: release

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;
        gcc --version
        cmake --version

    - name: run build.sh
      shell: bash
      run:
          sh build.sh

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output

