name: build

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  centos7:
    runs-on: ubuntu-latest
    container: centos:7
    env:
      OS_ENV: centos7

    steps:
    - name: prepare env
      run: |
        yum install -y epel-release
        yum install -y gcc-c++ cmake3 make wget autoconf automake libtool openssl-devel zlib-devel zip unzip
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;
        gcc --version
        cmake3 --version

    - name: build
      shell: bash
      run:
          sh build.sh

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: centos7
        path: output

  centos8:
    runs-on: ubuntu-latest
    container: centos:8
    env:
      OS_ENV: centos8

    steps:
    - name: prepare env
      run: |
        yum install -y gcc-c++ cmake make wget autoconf automake libtool openssl-devel zlib-devel zip unzip
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;
        gcc --version
        cmake3 --version
        export OS_ENV=centos8

    - name: build
      shell: bash
      run:
          sh build.sh

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: centos8
        path: output
