name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;
        gcc --version
        cmake --version

    - name: run build.sh
      shell: bash
      run:
          sh build.sh

    - name: make artifact
      run: |
        zip output.zip output/

    - name: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "output.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
