name: release

on:
  push:
    tags:
    - '*'

jobs:
  centos7:
    runs-on: ubuntu-latest
    container: centos:7
    env:
      OS_ENV: centos7

    steps:
    - name: prepare env
      run: |
        yum install -y epel-release
        yum install -y gcc-c++ cmake3 make wget autoconf automake libtool  openssl-devel zlib-devel
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;
        gcc --version
        cmake3 --version
        export OS_ENV=centos7

    - name: build
      shell: bash
      run:
          sh build.sh

    - name: make artifact
      run: |
        cd output;
        zip ../centos7.zip -r *;
        tar -czf ../centos7.tar.gz *;

    - name: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "centos7.zip,centos7.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}

  centos8:
    runs-on: ubuntu-latest
    container: centos:8
    env:
      OS_ENV: centos8

    steps:
    - name: prepare env
      run: |
        yum install -y gcc-c++ cmake make wget autoconf automake libtool openssl-devel zlib-devel
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo ${{runner.workspace}};
        echo $GITHUB_WORKSPACE;
        gcc --version
        cmake3 --version
        export OS_ENV=centos8

    - name: build
      shell: bash
      run:
          sh build.sh

    - name: make artifact
      run: |
        cd output;
        zip ../centos8.zip -r *;
        tar -czf ../centos8.tar.gz *;

    - name: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "centos8.zip,centos8.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
